/** @since ${NEXT_VERSION} */
import { 
    POSITIONAL_OPTIONS_KEY as DARGS_POSITIONAL_OPTIONS_KEY, 
    SEPARATED_OPTIONS_KEY as DARGS_SEPARATED_OPTIONS_KEY 
} from "./dargs.js";

/** @since ${NEXT_VERSION} */
export const POSITIONAL_OPTIONS_KEY = DARGS_POSITIONAL_OPTIONS_KEY;

/** @since ${NEXT_VERSION} */
export const SEPARATED_OPTIONS_KEY = DARGS_SEPARATED_OPTIONS_KEY;